spring:
  datasource:
    url: 'jdbc:postgresql://privacy-postgre.postgres.database.azure.com:5432/privacy'
    username: 'koyo@privacy-postgre'
    password: '!@#$QWER1234'
  jpa:
    hibernate:
      ddl-auto: update
