spring:
  datasource:
    url: 'jdbc:postgresql://privacy-postgre.postgres.database.azure.com:5432/privacy'
    username: 'koyo@privacy-postgre'
    password: '!@#$QWER1234'

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
    open-in-view: true

  mustache:
    suffix: .html
    cache: false

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  boot:
    admin:
      client:
        url: 'https://rs-privacy-admin.herokuapp.com'
        instance:
          service-base-url: 'https://rs-privacy.azurewebsites.net/'
          metadata:
            user:
              name: 'azureadmin'
              password: '@#$%WERT2345'
        username: 'herokuadmin'
        password: '#$%^ERTY3456'

  security:
    user:
      name: 'azureadmin'
      password: '$2a$10$o5JzuTK2IMUCAUTVx5YPD.TTBXUq8rHWOkSwNcZlMVpK/ScuL6fnO'

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full
