spring:
  datasource:
    url: 'jdbc:postgresql://privacy-postgre.postgres.database.azure.com:5432/privacy'
    username: 'koyo@privacy-postgre'
    password: '!@#$QWER1234'

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
    open-in-view: true

  mustache:
    suffix: .html
    cache: false

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  boot:
    admin:
      client:
        url: 'https://rs-privacy-admin.azurewebsites.net'
        instance:
          metadata:
            user:
              name: 'joe'
              password: 'my-secret-password'
        username: 'admin'
        password: 'admin-password'

  security:
    user:
      name: 'joe'
      password: 'my-secret-password'

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
